name: Lint & Test

on:
  workflow_call:
  pull_request:
    branches:
      - main
      - beta
      - '+([0-9])?(.{+([0-9]),x}).x'

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16.x, 18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: Checkout project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Check codestyle compliance
        run: npm run lint
      - name: Run tests
        run: npm run test
